title: Natura Himalayas
subtitle: Glimpage of Himalayan nature
author:
  name: Dr. Aaratrik Pal
  email: 
description: About Himalayan biodiversity, focusing on flowering plants and flying jewels (butterflies, damselflies, and dragonflies).


remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: auto

  nav_pages:
    - index.md
    - butterflies.md
    - odonates.md
    - photography.md
    - about.md
    # - portfolio.md

  show_excerpts: true

  date_format: "%b %-d, %Y"

  social_links:
  - title: Natura Himalayas on Instagram
    icon: instagram
    url: "https://www.instagram.com/natura_himalayas"
  - title: Aaratrik Pal on Flickr
    icon: flickr
    url: "https://www.flickr.com/photos/161022353@N02"
  #- title: Aaratrik Pal at GitHub
  #  icon: github
  #  url: "https://github.com/naturahimalayas"
  - title: Natura Himalayas on YouTube
    icon: youtube
    url: "https://www.youtube.com/@natura_himalayas"

    hide_site_feed_link: true
