title: Natura Himalayas
author:
name: Aaratrik Pal
email: 
description: About Himalayan biodiversity, focusing of flowering plants and flying jewels (butterflies, damselflies, and dragonflies).
instagram_username: natura_himalayas
youtube_username: natura_himalayas
github_username:  naturahimalayas

minima:
  skin: solarized-light
  date_format: "%b %-d, %Y"
  
   
remote_theme: "jekyll/minima@1e8a445"
plugins:
- jekyll-feed
- jekyll-seo-tag

 social_links:
    #  - { platform: devto,          user_url: "https://dev.to/jekyll" }
    #  - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
    #  - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
    - { platform: flickr,         user_url: "https://www.flickr.com/photos/161022353@N02" }
    - { platform: github, user_url: "https://github.com/naturahimalayas" }
    #  - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
    - { platform: instagram,      user_url: "https://www.instagram.com/natura_himalayas" }
    #  - { platform: keybase,        user_url: "https://keybase.io/naturahimalayas" }
    - { platform: youtube,        user_url: "https://www.youtube.com/natura_himalayas" }
