title: Natura Himalayas
author:
name: Aaratrik Pal
email: 
description: About Himalayan biodiversity, focusing of flowering plants and flying jewels (butterflies, damselflies, and dragonflies).

minima:
  skin: solarized-light
  date_format: "%b %-d, %Y"
  social_links:
    github: naturahimalayas
    instagram: natura_himalayas
    linkedin: 
    youtube: natura_himalayas
   
remote_theme: "jekyll/minima@1e8a445"
plugins:
- jekyll-feed
- jekyll-seo-tag
